server:
  tomcat:
    max-threads: 1
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 8000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
spring:
   liquibase:
      enabled: true
      change-log: classpath:db/master.xml
      default-schema: test
   redis:
      host: 172.16.40.21
      password:
      port: 6379
      database: 13
      jedis:
        pool:
          max-active: 200
          max-idle: 20
          min-idle: 5
          max-wait: 50ms
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     password: 12345678
     url: jdbc:mysql://192.168.116.128:3306/test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&useSSL=false
     username: root
     druid:
       initial-size: 5
       min-idle: 10
       max-active: 30
       max-wait: 60000
       time-between-eviction-runs-millis: 10000
       min-evictable-idle-time-millis: 300000
       filters: stat,wall,log4j,config
       validation-query: select 1
       validation-query-timeout: 3000
       pool-prepared-statements: true
       max-open-prepared-statements: 50
       max-pool-prepared-statement-per-connection-size: 20
       test-while-idle: true
       test-on-borrow: false
       test-on-return: false
       web-stat-filter:
         enabled: true
         url-pattern: /test/*
       stat-view-servlet:
         enabled: true
         url-pattern: /druid/*
         login-username: admin
         login-password: admin
       default-auto-commit: false
#mybatis:
#  type-aliases-package: com.example.domain.model
#  type-handlers-package: com.example.typehandler
#  configuration:
#      map-underscore-to-camel-case: true
#      default-fetch-size: 100

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
#      default-statement-timeout: 30
