eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    instance-id:  ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 2
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
